### ISSUE TITLE
CommandError: Error rendering template to disk

### ISSUE THREAD

**Issue by Etilem** [bckohan/django-render-static#143]
Hello and thanks for your work

I can't manage to execute the command : 

`$ manage.py renderstatic`

the error reported is : 

`CommandError: Error rendering template to disk: landing/home.html`

here's my django project tree :

```
src
├── db
├── landing
│   ├── migrations
│   ├── static
│   │   └── landing
│   │       ├── css
│   │       ├── fonts
│   │       ├── img
│   │       └── js
│   ├── templates
│   │   └── landing
│   │       └── home.html
├── src
└── static
```

content related to django-render-static package of src/settings.py :

```
INSTALLED_APPS = [
    'render_static',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates/",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_TEMPLATES = {
    'templates': ['landing/home.html']
}

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'
```
could you help me ?

**Comment by bckohan** [comment]
Hi @Etilem thanks for giving the library a try! **By default the static template engine searches for static templates in a directory called static_templates.** **So if you rename your ```templates``` directory to ```static_templates``` it should work for you.** 

Alternatively you can[ configure the directory loaders will look in](https://django-render-static.readthedocs.io/en/latest/configuration.html). Understand that the static templates engine is a close mirror of the normal templates configuration. This means the STATIC_TEMPLATES setting looks very similar to the TEMPLATES setting, but they are completely separate. STATIC_TEMPLATES controls the static templates rendering (at package or deployment time) and TEMPLATES controls Django's dynamic templates (at serving time).

Here is an example configuration that would make renderstatic look in the templates directory instead:

```python
STATIC_TEMPLATES = {
  'ENGINES': [
      'BACKEND': 'render_static.backends.StaticDjangoTemplates',
      'OPTIONS': {
          'app_dir': 'templates',  # search this directory in apps for templates
          'loaders': [
              'render_static.loaders.StaticAppDirectoriesBatchLoader',
           ],
          'builtins': ['render_static.templatetags.render_static']
      },
  ],
  'templates': ['landing/home.html']
}
```

**Comment by Etilem** [comment]
thank you for the comprehensive answer, it works indeed with :

```
STATIC_TEMPLATES = {
    'ENGINES': [{
        'BACKEND': 'render_static.backends.StaticDjangoTemplates',
        'OPTIONS': {
            'app_dir': 'templates',  # search this directory in apps for templates
            'loaders': ['render_static.loaders.StaticAppDirectoriesBatchLoader'],
            'builtins': ['render_static.templatetags.render_static']
        },
    }],
    'templates': ['landing/home.html']
}
```

by the way, there's a typo in documentation at line 56 of https://github.com/bckohan/django-render-static/blob/main/doc/source/configuration.rst?plain=1, it says `STATIC_TEMPALTES` instead of `STATIC_TEMPLATES`
